# Generated by Django 5.2.4 on 2025-07-30 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=200)),
                ('course', models.CharField(choices=[('hr', 'Human Resources'), ('it', 'Information Technology'), ('sales', 'Sales'), ('marketing', 'Marketing'), ('finance', 'Finance')], max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('hire_date', models.DateField()),
            ],
        ),
    ]
